# Generated by Django 5.2.4 on 2025-07-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type', models.CharField(choices=[('incidents', 'Incidents Data'), ('traffic_flow', 'Traffic Flow Data'), ('combined', 'Combined Data Collection')], max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('bbox', models.CharField(help_text='Bounding box used for data collection', max_length=200)),
                ('total_records_found', models.IntegerField(default=0)),
                ('new_records_created', models.IntegerField(default=0)),
                ('existing_records_updated', models.IntegerField(default=0)),
                ('errors_encountered', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveIncidentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomtom_incident_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('location_description', models.TextField(blank=True)),
                ('road_numbers', models.JSONField(default=list, help_text='Road numbers affected')),
                ('incident_type', models.CharField(db_index=True, max_length=50)),
                ('icon_category', models.CharField(db_index=True, max_length=50)),
                ('severity_code', models.CharField(db_index=True, max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('last_report_time', models.DateTimeField(blank=True, null=True)),
                ('magnitude_of_delay', models.CharField(blank=True, max_length=20)),
                ('length', models.FloatField(blank=True, help_text='Length of affected road in meters', null=True)),
                ('delay', models.IntegerField(blank=True, help_text='Delay in seconds', null=True)),
                ('probability_of_occurrence', models.FloatField(blank=True, null=True)),
                ('number_of_reports', models.IntegerField(default=0)),
                ('raw_api_data', models.JSONField(help_text='Complete raw response from TomTom API')),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('weather_conditions', models.CharField(blank=True, max_length=100)),
                ('time_of_day', models.CharField(blank=True, max_length=20)),
                ('day_of_week', models.CharField(blank=True, max_length=15)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this data has been processed for ML')),
            ],
            options={
                'verbose_name': 'Live Incident Data',
                'verbose_name_plural': 'Live Incident Data',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['tomtom_incident_id'], name='incidents_l_tomtom__d86841_idx'), models.Index(fields=['collected_at'], name='incidents_l_collect_f6f243_idx'), models.Index(fields=['city', 'incident_type'], name='incidents_l_city_ddc235_idx'), models.Index(fields=['latitude', 'longitude'], name='incidents_l_latitud_6c4b65_idx'), models.Index(fields=['start_time', 'end_time'], name='incidents_l_start_t_28aba8_idx'), models.Index(fields=['is_active', 'is_processed'], name='incidents_l_is_acti_e850ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficFlowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10)),
                ('current_speed', models.FloatField(help_text='Current speed in km/h')),
                ('free_flow_speed', models.FloatField(help_text='Free flow speed in km/h')),
                ('current_travel_time', models.IntegerField(help_text='Current travel time in seconds')),
                ('free_flow_travel_time', models.IntegerField(help_text='Free flow travel time in seconds')),
                ('congestion_ratio', models.FloatField(help_text='Current speed / Free flow speed')),
                ('delay_factor', models.FloatField(help_text='Current time / Free flow time')),
                ('road_closure', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('road_name', models.CharField(blank=True, max_length=255)),
                ('time_of_day', models.CharField(blank=True, max_length=20)),
                ('day_of_week', models.CharField(blank=True, max_length=15)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('weather_conditions', models.CharField(blank=True, max_length=100)),
                ('raw_api_data', models.JSONField(help_text='Complete raw response from TomTom API')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this data has been processed for ML')),
            ],
            options={
                'verbose_name': 'Traffic Flow Data',
                'verbose_name_plural': 'Traffic Flow Data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='incidents_t_latitud_d310a7_idx'), models.Index(fields=['timestamp'], name='incidents_t_timesta_39db45_idx'), models.Index(fields=['city', 'time_of_day'], name='incidents_t_city_d9a5bf_idx'), models.Index(fields=['collected_at'], name='incidents_t_collect_e049ad_idx'), models.Index(fields=['is_processed'], name='incidents_t_is_proc_caae8f_idx')],
            },
        ),
    ]
