# Generated by Django 5.2.4 on 2025-07-06 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('start_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('end_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('end_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('distance', models.FloatField(help_text='Distance in kilometers')),
                ('estimated_time', models.IntegerField(help_text='Estimated time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('density', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('flow', models.CharField(choices=[('smooth', 'Smooth'), ('moderate', 'Moderate'), ('congested', 'Congested'), ('gridlock', 'Gridlock')], default='smooth', max_length=20)),
                ('speed', models.FloatField(help_text='Average speed in km/h')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Traffic Data',
                'verbose_name_plural': 'Traffic Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrafficPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('predicted_density', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('predicted_flow', models.CharField(choices=[('smooth', 'Smooth'), ('moderate', 'Moderate'), ('congested', 'Congested'), ('gridlock', 'Gridlock')], max_length=20)),
                ('predicted_speed', models.FloatField(help_text='Predicted average speed in km/h')),
                ('confidence', models.FloatField(help_text='Prediction confidence (0-1)')),
                ('prediction_time', models.DateTimeField(help_text='Time this prediction is for')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Traffic Prediction',
                'verbose_name_plural': 'Traffic Predictions',
                'ordering': ['-prediction_time'],
            },
        ),
    ]
