# Generated by Django 5.2.4 on 2025-07-09 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('location', 'Location Report'), ('route', 'Route Report'), ('city', 'City Report')], default='location', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('traffic_data', models.JSONField(help_text='Raw traffic data from TomTom API')),
                ('ai_analysis', models.TextField(help_text='AI-generated traffic analysis')),
                ('ai_recommendations', models.TextField(help_text='AI-generated recommendations')),
                ('congestion_level', models.IntegerField(help_text='Congestion level percentage (0-100)')),
                ('avg_speed', models.FloatField(help_text='Average speed in km/h')),
                ('incident_count', models.IntegerField(help_text='Number of incidents in the area')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traffic Report',
                'verbose_name_plural': 'Traffic Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
