# Generated by Django 5.2.4 on 2025-07-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_trafficreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficreport',
            name='ai_analysis',
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='city',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='download_url',
            field=models.URLField(blank=True, help_text='URL to download the generated report'),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='file_size',
            field=models.CharField(blank=True, help_text="File size (e.g., '2.4 MB')", max_length=20),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='incident_analysis',
            field=models.TextField(blank=True, help_text='AI-generated incident analysis'),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='insights',
            field=models.JSONField(default=dict, help_text='Report insights and metrics'),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='peak_hours_analysis',
            field=models.TextField(blank=True, help_text='AI-generated peak hours analysis'),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='route_performance',
            field=models.TextField(blank=True, help_text='AI-generated route performance analysis'),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Failed')], default='generating', max_length=20),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='traffic_overview',
            field=models.TextField(blank=True, help_text='AI-generated traffic overview'),
        ),
        migrations.AlterField(
            model_name='trafficreport',
            name='ai_recommendations',
            field=models.TextField(blank=True, help_text='AI-generated recommendations'),
        ),
        migrations.AlterField(
            model_name='trafficreport',
            name='avg_speed',
            field=models.FloatField(default=0.0, help_text='Average speed in km/h'),
        ),
        migrations.AlterField(
            model_name='trafficreport',
            name='congestion_level',
            field=models.IntegerField(default=0, help_text='Congestion level percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='trafficreport',
            name='incident_count',
            field=models.IntegerField(default=0, help_text='Number of incidents in the area'),
        ),
        migrations.AlterField(
            model_name='trafficreport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trafficreport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trafficreport',
            name='report_type',
            field=models.CharField(choices=[('traffic_summary', 'Daily Traffic Summary'), ('incident_analysis', 'Incident Analysis Report'), ('route_performance', 'Route Performance Report'), ('city_comparison', 'City Comparison Report'), ('predictive', 'Predictive Analytics Report'), ('custom', 'Custom Report')], default='traffic_summary', max_length=20),
        ),
        migrations.AlterField(
            model_name='trafficreport',
            name='traffic_data',
            field=models.JSONField(default=dict, help_text='Raw traffic data from TomTom API'),
        ),
    ]
